return { -- this table overrides highlights in all themes
  -- Normal = { bg = "#000000" },
  TabLineSel = { fg = "aqua" },
  TelescopeResultsBorder = { fg = "aqua" },
  TelescopePreviewBorder = { fg = "aqua" },
  TelescopePromptBorder = { fg = "aqua" },
  Function = { fg = "#dcccab" },
  variable = { fg = "lightblue" },
  Variable = { fg = "lightblue" },
  attribute = { fg = "#56b6c2" },
  Attribute = { fg = "#56b6c2" },
  property = { fg = "lightblue" },
  Property = { fg = "lightblue" },
  Field = { fg = "lightblue" },
  field = { fg = "lightblue" },
  CursorLine = { bg = "Black" },
  CursorLineNC = { bg = "#1e222a" },
  NeoTreeCursorLine = { bg = "Black" },
  AerialLine = { bg = "Black" },
  Identifier = { fg = "pink" },
  identifier = { fg = "pink" },
  Normal = { bg = "#1e1e1e", fg = "white" },
  NeoTreeNormal = { bg = "#1e1e1e" },
  NormalNC = { bg = "#191919" },
  NeoTreeNormalNC = { bg = "#191919" },
  DiagnosticInfo = { fg = "orange" },
  Method = { fg = "#dcdcaa" },
  Parameter = { fg = "lightblue" },
  Constructor = { fg = "#e06c75" },
  CursorLineNr = { fg = "lightpink gui=none" },
}
